# Copyright lowRISC contributors.
#
# SPDX-License-Identifier: MIT
{
  pkgs,
  ncurses5-fhs,
  ncurses6-fhs,
  bazel_ot,
  python_ot,
  verilator_ot,
  verible_ot,
  lowrisc-toolchain-gcc-rv32imcb,
  edaTools ? [],
  wrapCCWith,
  gcc-unwrapped,
  pkg-config,
  symlinkJoin,
  extraPkgs ? [],
  ...
}: let
  # These dependencies are required for building user DPI C/C++ code, and cosimulation models.
  edaExtraDeps = with pkgs; [elfutils openssl python_ot];

  gcc-patched = wrapCCWith {
    cc = gcc-unwrapped;
    nixSupport = {
      cc-cflags = [
        # Bazel rules_rust expects build PIE binary in opt build but doesn't request PIE/PIC, so force PIC
        "-fPIC"
        # Bazel filters out environment variables, so add this one back. ldflags is similar.
        "-idirafter /usr/include"
      ];
      cc-ldflags = ["-L/usr/lib" "-L/usr/lib32"];
    };
  };

  # Bazel filters out all environment including PKG_CONFIG_PATH. Append this inside wrapper.
  pkg-config-patched = pkg-config.override {
    extraBuildCommands = ''
      echo "export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/pkgconfig" >> $out/nix-support/utils.bash
    '';
  };

  # Wrap automake's aclocal to set the default macro search path to the FHSenv pre-populated value
  # The nixpkgs default is to use ACLOCAL_PATH to override this default, but this avoids passing another
  # environment into the sandbox non-hermetically.
  automake' = pkgs.automake.overrideAttrs (oldAttrs: {
    nativeBuildInputs = (oldAttrs.nativeBuildInputs or []) ++ [pkgs.makeWrapper];
    postFixup =
      (oldAttrs.postFixup or "")
      + ''
        wrapProgram $out/bin/aclocal --add-flags "--system-acdir=/usr/share/aclocal"
      '';
  });
in
  (pkgs.buildFHSEnvOverlay {
    pname = "opentitan";
    version = "dev";
    targetPkgs = _:
      with pkgs;
        [
          bazel_ot
          verilator_ot
          verible_ot

          # Python dependencies
          python_ot

          # For serde-annotate which can be built with just cargo
          rustup

          # For the OTBN simulator
          ninja
          # 'as' needed for the OTBN assembler
          lowrisc-toolchain-gcc-rv32imcb

          # dvsim uses git for logging/tagging purposes
          gitFull
          gnumake

          # Needed by sw/host/cryptotest/testvectors/data/BUILD
          unzip

          # Needed by OT-lib xmodem tests
          lrzsz

          # Bazel downloads Rust compilers which are not patchelfed and they need this.
          zlib
          openssl
          curl
          util-linux # flock for bazelisk
          file # needed by rules_rust

          # Provide static libraries needed for statically-linking verilator models and OTT
          zlib.static
          glibc.static
          (openssl.override {static = true;})

          # Deps for building sc_hsm
          autoconf
          automake'
          libtool
          pcsclite.lib
          gnum4

          gcc-patched
          pkg-config-patched

          libxcrypt-legacy
          udev
          libftdi1
          (libusb1.override {withStatic = true;}) # needed for libftdi1 pkg-config
          glib

          # Somehow if you have both then FHS env building recurses forever, so
          # symlink join them together first.
          (symlinkJoin {
            name = "ncurses";
            paths = [ncurses5-fhs ncurses6-fhs];
          })

          srecord

          # For documentation
          hugo
          doxygen
          libxslt # util/mdbook/difgen.py, requires `xsltproc` to be in the path.
        ]
        # Binaries generated by the EDA tools do no have RPATH set so they also need runtime deps.
        ++ edaExtraDeps
        # EDA tools are themselves wrapped inside a FHS env, which recreates FHS paths (/bin, /lib, ...) afresh.
        # This means that they can't see tools added to FHS paths in this "opentitan" env.
        # As a workaround, pass these dependencies as an `extraDependencies` arg into them.
        ++ map (tool:
          tool.override {
            extraDependencies = edaExtraDeps;
          })
        edaTools
        ++ extraPkgs;
    extraOutputsToInstall = ["dev"];

    # Bazel downloads pre-built host tools (Rust toolchain, curl, etc.) that were
    # compiled on a standard FHS Linux system with OPENSSLDIR=/etc/ssl baked in at
    # compile time. These unpatched binaries look for openssl.cnf and the CA trust
    # bundle at /etc/ssl regardless of any environment variables, since Bazel's
    # sandbox strips most env vars (including SSL_CERT_FILE) before running actions.
    preExecHook = ''
      # Only populate openssl.cnf if it is absent or a dangling symlink, indicated
      # by [ -e ] returning false (it follows symlinks, so a dangling symlink to a
      # garbage-collected Nix store path on NixOS will also fail this test).
      # A valid host file is preserved to retain any system-specific crypto policy:
      # Fedora/RHEL include /etc/crypto-policies/back-ends/opensslcnf.config via
      # an .include directive, and Debian/Ubuntu configure SECLEVEL and MinProtocol.
      if ! [ -e /etc/ssl/openssl.cnf ]; then
        ln -sf ${pkgs.openssl.out}/etc/ssl/openssl.cnf /etc/ssl/openssl.cnf
      fi

      # Populate /etc/ssl/cert.pem if absent or dangling, trying CA bundle
      # locations used by common distributions in order of preference.
      if ! [ -e /etc/ssl/cert.pem ]; then
        for ca_bundle in \
          /etc/ssl/certs/ca-certificates.crt \
          /etc/pki/tls/certs/ca-bundle.crt \
          /etc/ssl/certs/ca-bundle.crt \
          /etc/ssl/ca-bundle.pem; do
          if [ -f "$ca_bundle" ]; then
            ln -sf "$ca_bundle" /etc/ssl/cert.pem
            break
          fi
        done
      fi
    '';

    profile = ''
      # Workaround bazel bug: https://github.com/bazelbuild/bazel/issues/23217
      export TMPDIR=/tmp
      # This is already handled by wrappers
      unset NIX_CFLAGS_COMPILE
      unset NIX_CFLAGS_LINK
      unset NIX_LDFLAGS
      unset PKG_CONFIG_PATH
    '';

    runScript = "\${SHELL:-bash}";
  })
  .env
