# Copyright lowRISC Contributors.
# Licensed under the MIT License, see LICENSE for details.
# SPDX-License-Identifier: MIT
{
  inputs,
  pkgs,
  python310,
  lib,
  ...
}: let
  # This overlay is generated by poetry2nix
  poetry-git-overlay = import ./poetry-git-overlay.nix {inherit pkgs;};

  poetry2nix = inputs.poetry2nix.lib.mkPoetry2Nix {inherit pkgs;};
  poetryOverrides = inputs.self.lib.poetryOverrides {inherit pkgs;};

  env = poetry2nix.mkPoetryEnv {
    projectDir = ./.;
    python = python310;
    overrides = [
      poetry-git-overlay
      poetryOverrides
      poetry2nix.defaultPoetryOverrides
    ];
  };
in
  env
  // {
    meta =
      env.meta
      // {
        platforms = lib.platforms.linux;
      };
  }
