# Copyright lowRISC Contributors.
# Licensed under the MIT License, see LICENSE for details.
# SPDX-License-Identifier: MIT
#
# Generic EDA development shell builder.
#
# A project declares only *which* vendor tools + versions it needs. All
# site-specific data (NFS install paths, license servers, per-tool layout,
# runtime workarounds) is supplied at *runtime* from a JSON config file pointed
# to by an environment variable (default `LOWRISC_EDA_CONFIG`). This keeps the
# builder — and any public flake that imports it — free of vendor/site secrets,
# and lets anyone use the shell by writing their own config.
#
# If the config file is absent the shell still works (base Nix tools remain on
# PATH); it just prints a warning and configures no EDA tools.
#
# Config JSON schema (see README.md for the full contract):
#   {
#     "vendors": {
#       "<vendor>": {
#         "license": { "envVars": { "<ENV_VAR>": "<value>", ... } },
#         "tools": {
#           "<tool>": {
#             "homeVar":     "<ENV_VAR>",               # optional
#             "pathDirs":    ["bin", ...],              # optional, default ["bin"]
#             "executables": ["<exe>", ...],            # optional
#             "extraEnvVars":{ "<ENV_VAR>": "<value>" },# optional
#             "extraPaths":  { "<ENV_VAR>": "<subdir>" },# optional (prepend home/subdir)
#             "requires":    ["<tool>", ...],           # optional
#             "capabilities":{ "ldPreload": "gmp",      # optional, allowlisted
#                              "ldRelink": ["<glob>"] },#   (see Capabilities)
#             "versions": { "<version>": { "home": "<abs path>" }, ... }
#           }
#         }
#       }
#     }
#   }
#
# Runtime values are read from jq as newline-delimited records (tab-separated
# for key/value maps) and assigned as data (export "$k=$v") — the script never
# `eval`s config content, so version strings, license values with '@', etc. are
# safe. Config values are assumed free of embedded newlines/tabs (true for all
# tool paths, env-var names and license strings).
{
  pkgs,
  lib ? pkgs.lib,
  # Human-readable shell / FHS pname.
  name,
  # Requested tools: { <vendor>.<tool> = "<version>"; ... }
  tools,
  # Environment variable naming the runtime config file.
  configEnvVar ? "LOWRISC_EDA_CONFIG",
  # Extra packages added to the FHS env (build/runtime deps for the project).
  extraDeps ? [],
  extraPkgs ? [],
  # Project profile fragment, appended after the EDA setup.
  profile ? "",
}: let
  # Build the FHS-env wrapper from the given pkgs, so consumers don't need to
  # add the buildFHSEnvOverlay overlay to their package set themselves.
  buildFHSEnvOverlay = pkgs.callPackage ./buildFHSEnvOverlay.nix {};

  edaFhsPackages = import ./edaFhsPackages.nix {inherit pkgs;};

  # Flatten { vendor.tool = version; } into a list of {vendor;tool;version;}.
  requested = lib.flatten (
    lib.mapAttrsToList (
      vendor: toolset:
        lib.mapAttrsToList (tool: version: {inherit vendor tool version;}) toolset
    )
    tools
  );

  # Baked manifest the runtime script iterates. Vendor/tool/version tokens are
  # whitespace-free across our tool data, so a space-delimited triple is safe.
  manifestLines =
    lib.concatMapStringsSep "\n"
    (r: ''"${r.vendor} ${r.tool} ${r.version}"'')
    requested;

  # Capability implementations the builder knows about (mechanisms, not vendors).
  # The config only *names* a capability; the actual Nix-store bits come from here.
  gmpLib = "${lib.getLib pkgs.gmp}/lib/libgmp.so.10";

  # System-linker shim. Some vendor gcc toolchains ship a linker too old for
  # modern relative relocations; the `ldRelink` capability lists (globs of)
  # bundled linkers to bind-replace with this shim (see edaPreExec below).
  ldWrapper = pkgs.writeShellScript "eda-ld" ''
    # Unset LD_LIBRARY_PATH so the system ld uses its own RPATH rather than the
    # tool's bundled libraries.
    unset LD_LIBRARY_PATH
    exec /usr/bin/ld "$@"
  '';
  jqBin = "${pkgs.jq}/bin/jq";

  # Runtime EDA environment setup. Escaping: bash `${...}` is written `''${...}`;
  # `\t` is passed literally to jq, which emits a real tab in its output.
  edaProfile = ''
    # ------------------------------------------------------------------ #
    # lowRISC generic EDA environment setup (generated by mkEdaShell)     #
    # ------------------------------------------------------------------ #
    _eda_cfg="''${${configEnvVar}:-}"
    if [ -z "$_eda_cfg" ] || [ ! -f "$_eda_cfg" ]; then
      echo "WARNING: EDA tool config env var ${configEnvVar} ('$_eda_cfg') not set or not found." >&2
      echo "         No EDA tools configured; base shell tools are still available." >&2
    else
      _eda_requested=(
    ${manifestLines}
      )
      _eda_vendors_seen=()

      # Apply an allowlisted capability for one tool. Mechanisms only — the
      # config never supplies executable code.
      _eda_apply_caps() {
        local v="$1" t="$2" home="$3"
        local cap exe real wrapdir
        cap=$(jq -r --arg v "$v" --arg t "$t" \
          '.vendors[$v].tools[$t].capabilities.ldPreload // empty' "$_eda_cfg")
        if [ "$cap" = "gmp" ]; then
          # Wrap this tool's executables so they LD_PRELOAD the FHS gmp without
          # perturbing every process in the shared shell. The real binaries are
          # already on PATH (prepended above), so resolve + shadow them.
          wrapdir=$(mktemp -d)
          while IFS= read -r exe; do
            [ -z "$exe" ] && continue
            real=$(command -v "$exe" 2>/dev/null) || continue
            {
              echo '#!/bin/sh'
              echo "export LD_PRELOAD=${gmpLib}"
              echo "exec \"$real\" \"\$@\""
            } > "$wrapdir/$exe"
            chmod +x "$wrapdir/$exe"
          done < <(jq -r --arg v "$v" --arg t "$t" \
            '(.vendors[$v].tools[$t].executables // [])[]' "$_eda_cfg")
          export PATH="$wrapdir:$PATH"
        fi
      }

      # Configure one tool from the config.
      _eda_setup_one() {
        local v="$1" t="$2" ver="$3"
        local home homeVar userVar d k val req exe

        home=$(jq -r --arg v "$v" --arg t "$t" --arg ver "$ver" \
          '.vendors[$v].tools[$t].versions[$ver].home // empty' "$_eda_cfg")
        if [ -z "$home" ]; then
          echo "WARNING: EDA tool $v/$t/$ver not present in config; skipping." >&2
          return 0
        fi

        homeVar=$(jq -r --arg v "$v" --arg t "$t" \
          '.vendors[$v].tools[$t].homeVar // empty' "$_eda_cfg")

        # Allow a user to override the install directory via USER_<HOMEVAR>.
        if [ -n "$homeVar" ]; then
          userVar="USER_$homeVar"
          if [ -n "''${!userVar:-}" ]; then
            echo "$homeVar taken from the user environment via $userVar."
            home="''${!userVar}"
          fi
        fi

        if [ ! -d "$home" ]; then
          echo "WARNING: EDA tool $v/$t home ($home) does not exist; skipping." >&2
          return 0
        fi

        [ -n "$homeVar" ] && export "$homeVar=$home"

        # pathDirs: prepend $home/<dir> to PATH (default ["bin"]).
        while IFS= read -r d; do
          [ -z "$d" ] && continue
          export PATH="$home/$d:$PATH"
        done < <(jq -r --arg v "$v" --arg t "$t" \
          '(.vendors[$v].tools[$t].pathDirs // ["bin"])[]' "$_eda_cfg")

        # extraEnvVars: literal VAR=value. Read as data, never eval.
        while IFS="$(printf '\t')" read -r k val; do
          [ -z "$k" ] && continue
          export "$k=$val"
        done < <(jq -r --arg v "$v" --arg t "$t" \
          '(.vendors[$v].tools[$t].extraEnvVars // {}) | to_entries[] | "\(.key)\t\(.value)"' "$_eda_cfg")

        # extraPaths: VAR gets $home/<subdir> prepended.
        while IFS="$(printf '\t')" read -r k val; do
          [ -z "$k" ] && continue
          export "$k=$home/$val''${!k:+:''${!k}}"
        done < <(jq -r --arg v "$v" --arg t "$t" \
          '(.vendors[$v].tools[$t].extraPaths // {}) | to_entries[] | "\(.key)\t\(.value)"' "$_eda_cfg")

        _eda_apply_caps "$v" "$t" "$home"

        # Warn if a declared companion tool is not part of this shell.
        while IFS= read -r req; do
          [ -z "$req" ] && continue
          if ! printf '%s\n' "''${_eda_requested[@]}" | grep -q " $req "; then
            echo "WARNING: $v/$t requires '$req', which is not in this shell's tool set." >&2
          fi
        done < <(jq -r --arg v "$v" --arg t "$t" \
          '(.vendors[$v].tools[$t].requires // [])[]' "$_eda_cfg")

        # Non-fatal sanity check: each executable should resolve on the new PATH.
        while IFS= read -r exe; do
          [ -z "$exe" ] && continue
          if ! command -v "$exe" >/dev/null 2>&1; then
            echo "WARNING: executable '$exe' for $v/$t not found after PATH setup." >&2
          fi
        done < <(jq -r --arg v "$v" --arg t "$t" \
          '(.vendors[$v].tools[$t].executables // [])[]' "$_eda_cfg")

        _eda_vendors_seen+=("$v")
      }

      for _entry in "''${_eda_requested[@]}"; do
        # Split into fields without touching the shell's positional parameters
        # ($@ is later used by the FHS env init to exec the shell/command).
        read -r _ev _et _ever <<< "$_entry"
        _eda_setup_one "$_ev" "$_et" "$_ever"
      done

      # Export each seen vendor's license vars once (only vendors that resolved).
      while IFS= read -r _v; do
        [ -z "$_v" ] && continue
        while IFS="$(printf '\t')" read -r _k _val; do
          [ -z "$_k" ] && continue
          export "$_k=$_val"
        done < <(jq -r --arg v "$_v" \
          '(.vendors[$v].license.envVars // {}) | to_entries[] | "\(.key)\t\(.value)"' "$_eda_cfg")
      done < <(printf '%s\n' "''${_eda_vendors_seen[@]}" | sort -u)

      unset -f _eda_setup_one _eda_apply_caps
      unset _eda_cfg _eda_requested _eda_vendors_seen _entry _ev _et _ever _v _k _val
    fi
  '';

  # Runs inside the FHS mount namespace, after `source /etc/profile` (so the
  # tool *_HOME vars are already exported) and before the shell is exec'd. Uses
  # the init-provided `bind` helper to replace each configured bundled linker
  # with the system-ld shim — this cannot be done from the profile, which has no
  # mount privileges. Reads the home from the exported homeVar (honouring any
  # USER_<HOMEVAR> override) and falls back to the config's resolved home.
  edaPreExec = ''
    _eda_cfg="''${${configEnvVar}:-}"
    if [ -n "$_eda_cfg" ] && [ -f "$_eda_cfg" ]; then
      _eda_relink=(
    ${manifestLines}
      )
      for _entry in "''${_eda_relink[@]}"; do
        read -r _v _t _ver <<< "$_entry"
        _hv=$(${jqBin} -r --arg v "$_v" --arg t "$_t" \
          '.vendors[$v].tools[$t].homeVar // empty' "$_eda_cfg")
        _home=""
        [ -n "$_hv" ] && _home="''${!_hv:-}"
        [ -z "$_home" ] && _home=$(${jqBin} -r --arg v "$_v" --arg t "$_t" --arg ver "$_ver" \
          '.vendors[$v].tools[$t].versions[$ver].home // empty' "$_eda_cfg")
        [ -z "$_home" ] && continue
        while IFS= read -r _glob; do
          [ -z "$_glob" ] && continue
          for _f in $_home/$_glob; do
            [ -e "$_f" ] && bind ${ldWrapper} "$_f"
          done
        done < <(${jqBin} -r --arg v "$_v" --arg t "$_t" \
          '(.vendors[$v].tools[$t].capabilities.ldRelink // [])[]' "$_eda_cfg")
      done
    fi
  '';
in
  (buildFHSEnvOverlay {
    pname = name;
    version = "eda";
    targetPkgs = _: edaFhsPackages ++ extraDeps ++ extraPkgs;
    extraOutputsToInstall = ["dev"];
    multiArch = true;
    runScript = "\${SHELL:-bash}";
    profile = edaProfile + "\n" + profile;
    preExecHook = edaPreExec;
  })
  .env
